jobs:
  include:
  - stage: Deploy
    if: branch = master
    name: Frontend
    language: node_js
    node_js: stable
    cache:
      directories:
      - node_modules
    env:
    - DEPLOY_PROVIDER=firebase
    script:  ember build --environment=production

deploy:
  - provider: firebase
    edge: true
    token: $FIREBASE_TOKEN
    on:
      branch: master
      condition: $DEPLOY_PROVIDER = firebase
